service: travel-service

frameworkVersion: "3"

useDotenv: true
deprecationNotificationMode: warn:summary

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-2
  iam:
    role: arn:aws:iam::369283419232:role/lambdaExecutionRole

functions:
  listWcChargers:
    handler: api/wcChargers.list
    memorySize: 128
    timeout: 15
    description: list nearby wheelchair chargers
    events:
      - http:
          path: wcChargers
          method: get
  listSpots:
    handler: api/spots.list
    memorySize: 512
    timeout: 30
    description: list nearby tourist spots with info on disabilities facilities
    events:
      - http:
          path: spots
          method: get
